# Generated by Django 4.0.1 on 2023-01-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annomalies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='post_2015_comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='survey_parcel_no',
            field=models.CharField(max_length=30),
        ),
    ]
